### ISSUE TITLE
Forced authentication methods  do not work?

### ISSUE THREAD

**Issue by basketas** [zeronetworks/cornershot#9]
I tried all the methods from cornershot 
`DEFAULT_SHOTS = [RPRNShot, EVENShot,  RRPShot, EVEN6Shot]`
The app chooses only **RPRNshots**, every time. Not sure if this is a bug or intentional?

Anyway, RPRN method is patched by Microsoft as far as I know, and it doesn't give any results nor attempts a connection in my lab. 
![image](https://user-images.githubusercontent.com/16399561/150700066-93b5f463-1cc9-4473-9870-e14357fbb7c6.png)

The other 3 methods only report false results, and only for port 445. Even though that port is closed as well as the other ones I am specifying in the command line. If I open the ports, the results are still the same...
![image](https://user-images.githubusercontent.com/16399561/150700242-58c02b9e-f531-4b14-b92c-7b467dd25736.png)

The custom_shot.py just freezes the console and no results appear no matter how long I wait.

**Comment by sagiesec** [comment]
Thanks for sharing @basketas . 

Please read the documentation about each shot, and which OS it should be expected to work on.
For example, RPRN is usually what you see because it can be used to scan any port number on Win 10 hosts. Other protocols are limited to port 445. As far as I know there is not patch for RPRN: you can record the traffic on a Win 10 "carrier" and see if traffic to the target is produced. 

Regarding the other methods, like I mentioned, they only scan port 445 like you noticed. There are situations in which the result is inconclusive and therefore "unknown". If you can share the pcap traffic from one of these shots from a carrier it would be helpful for debugging
